In [1]:
import numpy as np
import pandas as pd

### Merging 2 Dataframes

In [2]:
# DataFrame 1: Employee information
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary information
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [3]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [4]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [ ]:
# for merging dataframes there should be common in them like here we have employee_id
pd.merge(employees,salaries,on='employee_id',how="inner") #on means on what basis u want to merge
# the how thing by defaults use inner however u can see in the below cell the explaination of various joins

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

# Joins in merge (simple idea)

Think of 2 tables:
- Left table = employees
- Right table = salaries

You match them using employee_id.

1. Inner join
- Keeps only the rows that appear in both tables.
- Example: 1, 2, 3
- Memory: "only the overlap"

2. Left join
- Keeps all rows from the left table.
- Adds matching rows from the right table.
- If a left row has no match, it gets empty values.
- Example: 1, 2, 3, 4, 5
- Memory: "left side stays complete"

3. Right join
- Keeps all rows from the right table.
- Adds matching rows from the left table.
- Example: 1, 2, 3, 6, 7
- Memory: "right side stays complete"

4. Outer join
- Keeps all rows from both tables.
- Example: 1, 2, 3, 4, 5, 6, 7
- Memory: "everything from both"

5. Cross join
- Gives every row from the left table with every row from the right table.
- Memory: "all possible pairs"

Quick memory trick:
- Inner = overlap
- Left = left + overlap
- Right = right + overlap
- Outer = everything
- Cross = every combination

In pandas, this is controlled by:
- how='inner'
- how='left'
- how='right'
- how='outer'
- how='cross'

Note:
- The merge you already used is an Inner Join by default.

In [9]:
pd.merge(employees,salaries,on='employee_id',how="outer")

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [ ]:
pd.merge(employees,salaries,on='employee_id',how="left") 
# keeps the left column which is employee

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [ ]:
pd.merge(employees,salaries,on='employee_id',how="right") 
# keeps the right column based on salaries

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

### Concatination Of 2 Dataframes

In [12]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [13]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [14]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [15]:
# merging is done using concat function which merges two columns based on the column names
pd.concat([df2,df1])

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [16]:
# now lets concat them in rows
pd.concat([df1,df2],axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

### Joining Of 2 Dataframes

In [17]:
df1 = pd.DataFrame({
    'name' : ['Alice','Bob','Charliw']
},index = [1,2,3])
df2 = pd.DataFrame({
    'Score' : [85,90,75]
},index= [2,3,4])

In [ ]:
df1.join(df2)
# it uses the same how factor inner outer left right the same thing

      name  Score
1    Alice    NaN
2      Bob   85.0
3  Charliw   90.0

In [ ]:
df1.join(df2,how='outer')

      name  Score
1    Alice    NaN
2      Bob   85.0
3  Charliw   90.0
4      NaN   75.0

In [20]:
df1.join(df2,how='left')

      name  Score
1    Alice    NaN
2      Bob   85.0
3  Charliw   90.0

In [21]:
df1.join(df2,how='right')

      name  Score
2      Bob     85
3  Charliw     90
4      NaN     75