In [68]:
import pandas as pd

### EDA (exploartory data anylytics)

## Data Cleaning

### 
     -drop
     -fill

fill
    --> hardcoded values
    --> mean
    --> median
    --->mode

In [69]:
data = pd.read_excel("employee.xlsx")
data

    Serial  Emp_ID Designation  Department   Age    Salary
0        1    1101     Manager    Accounts  50.0  200000.0
1        2    1107     Officer          IT  30.0   80000.0
2        3    1203     Officer          HR  28.0       NaN
3        4    1005     Manager          HR  45.0  120000.0
4        5    2123  Office Boy    Accounts  27.0   45000.0
5        6    2451  Accountant         NaN  34.0  100000.0
6        7    1111  Accountant    Accounts   NaN  110000.0
7        8    1001     Officer          IT  25.0   75000.0
8        9    1234     Manager          IT  23.0       NaN
9       10    2156    Engineer  Production  45.0   89000.0
10      11    6543     Officer  Production  29.0  100000.0
11      12    3214  Accountant     Account  49.0  123000.0
12      13    2156    Engineer  Production  45.0   89000.0
13      14    1098     Officer          IT  25.0  100000.0
14      15    2912     Officer          IT  31.0   90000.0
15      16    1222     Officer         NaN  25.0       NaN
16      17    2156    Engineer  Production  45.0   89000.0
17      18    2123  Office Boy    Accounts  27.0   45000.0
18      19    2156    Engineer  Production  45.0   89000.0
19      20    6543     Officer  Production  29.0  100000.0
20      21    3214  Accountant     Account  49.0  123000.0
21      22    3214  Accountant     Account  49.0  123000.0
22      23    2156    Engineer  Production  45.0   89000.0
23      24    1098     Officer          IT  25.0  100000.0

In [70]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Serial       24 non-null     int64
 1   Emp_ID       24 non-null     int64
 2   Designation  24 non-null     str
 3   Department   22 non-null     str
 4   Age          23 non-null     float64
 5   Salary       21 non-null     float64
dtypes: float64(2), int64(2), str(2)
memory usage: 1.6 KB

In [71]:
data.columns

Index(['Serial', 'Emp_ID', 'Designation', 'Department', 'Age', 'Salary'], dtype='str')

In [72]:
data.shape

(24, 6)

In [73]:
data.isna().sum()

Serial         0
Emp_ID         0
Designation    0
Department     2
Age            1
Salary         3
dtype: int64

In [74]:
data.Designation.value_counts()

Designation
Officer       9
Accountant    5
Engineer      5
Manager       3
Office Boy    2
Name: count, dtype: int64

In [75]:
data.Age.min()

np.float64(23.0)

In [76]:
data.Age.max()

np.float64(50.0)

### Dropna

axis 0 --> rows
axis 1 ---> columns

any = data mai aik bhi column ki rows nan mil gaye

In [77]:
data.dropna(how="any")

    Serial  Emp_ID Designation  Department   Age    Salary
0        1    1101     Manager    Accounts  50.0  200000.0
1        2    1107     Officer          IT  30.0   80000.0
3        4    1005     Manager          HR  45.0  120000.0
4        5    2123  Office Boy    Accounts  27.0   45000.0
7        8    1001     Officer          IT  25.0   75000.0
9       10    2156    Engineer  Production  45.0   89000.0
10      11    6543     Officer  Production  29.0  100000.0
11      12    3214  Accountant     Account  49.0  123000.0
12      13    2156    Engineer  Production  45.0   89000.0
13      14    1098     Officer          IT  25.0  100000.0
14      15    2912     Officer          IT  31.0   90000.0
16      17    2156    Engineer  Production  45.0   89000.0
17      18    2123  Office Boy    Accounts  27.0   45000.0
18      19    2156    Engineer  Production  45.0   89000.0
19      20    6543     Officer  Production  29.0  100000.0
20      21    3214  Accountant     Account  49.0  123000.0
21      22    3214  Accountant     Account  49.0  123000.0
22      23    2156    Engineer  Production  45.0   89000.0
23      24    1098     Officer          IT  25.0  100000.0

In [78]:
data.isna().sum()

Serial         0
Emp_ID         0
Designation    0
Department     2
Age            1
Salary         3
dtype: int64

### Filter Data

In [79]:
data.head()

   Serial  Emp_ID Designation Department   Age    Salary
0       1    1101     Manager   Accounts  50.0  200000.0
1       2    1107     Officer         IT  30.0   80000.0
2       3    1203     Officer         HR  28.0       NaN
3       4    1005     Manager         HR  45.0  120000.0
4       5    2123  Office Boy   Accounts  27.0   45000.0

In [80]:
data.Department.isna().sum

<bound method Series.sum of 0     False
1     False
2     False
3     False
4     False
5      True
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15     True
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
Name: Department, dtype: bool>

In [81]:
data.Department.fillna(0)

0       Accounts
1             IT
2             HR
3             HR
4       Accounts
5              0
6       Accounts
7             IT
8             IT
9     Production
10    Production
11       Account
12    Production
13            IT
14            IT
15             0
16    Production
17      Accounts
18    Production
19    Production
20       Account
21       Account
22    Production
23            IT
Name: Department, dtype: object

### Mean,Median,Mode

    Categorical data: 
        Designation is a type of categorical data
        We use mode for categorical data. Wherever we spot this type of data we fill it using mode.
    Numerical data:
    - Data in numbers.
    - For numerical data we don’t use mode by default. We use measures of central tendency instead:
        1. Mean = Average
             - Add all numbers ÷ count of numbers.
             - Use it when data is balanced with no big outliers.
             - Ex: Salary data 30k, 35k, 32k → Mean ≈ 32.3k
        2. Median = Middle value
             - Sort data, pick the middle one. If even count, average the 2 middle values.
             - Use it when data has outliers or is skewed.
             - Ex: Salary data 30k, 32k, 1M → Median = 32k, but Mean gets pulled up by 1M
        3. Mode = Most frequent value
             - Works for numerical data too, but only useful if some number repeats a lot.
             - Ex: Test scores 70, 70, 75, 80 → Mode = 70

    In data cleaning/ML, most people use median for numerical missing values because it’s robust to outliers. Mean is used when data is normally distributed.

In [82]:
data.Department.mode()[0]
# MOST REPEATED VALUE

'Production'

In [83]:
data.Department.fillna(data.Department.mode()[0])

0       Accounts
1             IT
2             HR
3             HR
4       Accounts
5     Production
6       Accounts
7             IT
8             IT
9     Production
10    Production
11       Account
12    Production
13            IT
14            IT
15    Production
16    Production
17      Accounts
18    Production
19    Production
20       Account
21       Account
22    Production
23            IT
Name: Department, dtype: str

In [84]:
data.Age.isna().sum()

np.int64(1)

## Mean
    Avg of data
## Median
    [1,2,3,4,5,6] => 3.5

### Outliers
    [10,20,25,30,40,100] ---> outliers in data
    An outlier is a number in a dataset that is completely different from all the other numbers. It’s the "odd one out" that stands way too far away from the rest of the group.

    In your data: [10, 20, 25, 30, 40, 100]

    Most of the numbers are close together, sitting comfortably between 10 and 40.

    100 is the outlier because it is massively larger than everything else.

    If outlier is far then we will fill data using median
    If outlier is near then we will fill data using mean

In [85]:
data.Age.mean()

np.float64(35.869565217391305)

In [86]:
data.Age

0     50.0
1     30.0
2     28.0
3     45.0
4     27.0
5     34.0
6      NaN
7     25.0
8     23.0
9     45.0
10    29.0
11    49.0
12    45.0
13    25.0
14    31.0
15    25.0
16    45.0
17    27.0
18    45.0
19    29.0
20    49.0
21    49.0
22    45.0
23    25.0
Name: Age, dtype: float64

In [87]:
data.Age.mean()

np.float64(35.869565217391305)

In [88]:
import numpy as np

In [89]:
data.Salary

0     200000.0
1      80000.0
2          NaN
3     120000.0
4      45000.0
5     100000.0
6     110000.0
7      75000.0
8          NaN
9      89000.0
10    100000.0
11    123000.0
12     89000.0
13    100000.0
14     90000.0
15         NaN
16     89000.0
17     45000.0
18     89000.0
19    100000.0
20    123000.0
21    123000.0
22     89000.0
23    100000.0
Name: Salary, dtype: float64

In [90]:
any1 = data.Salary.fillna(2000)
any1

0     200000.0
1      80000.0
2       2000.0
3     120000.0
4      45000.0
5     100000.0
6     110000.0
7      75000.0
8       2000.0
9      89000.0
10    100000.0
11    123000.0
12     89000.0
13    100000.0
14     90000.0
15      2000.0
16     89000.0
17     45000.0
18     89000.0
19    100000.0
20    123000.0
21    123000.0
22     89000.0
23    100000.0
Name: Salary, dtype: float64

In [105]:
p = np.percentile(data.Salary,1.6)

In [92]:
data.Salary.quantile(0.25)

np.float64(89000.0)

In [93]:
q1 = np.percentile(data.Salary,25)
q1

np.float64(nan)

In [94]:
q3 = np.percentile(data.Salary,75)
q3

np.float64(nan)

In [95]:
iqr = q3 - q1

In [96]:
iqr

np.float64(nan)

In [97]:
lw = q1-1.5*iqr
lw

np.float64(nan)

In [98]:
hw = q3+1.5*iqr
hw

np.float64(nan)

In [99]:
data[(data.Salary<=lw) | (data.Salary>=hw)  ]

Empty DataFrame
Columns: [Serial, Emp_ID, Designation, Department, Age, Salary]
Index: []

### Clean Salary data

In [108]:
data.fillna({
    "Department" : data.Department.mode()[0],
    "Salary" : data.Salary.median(),
    "Age" : data.Age.mean()
},inplace = True)

    Serial  Emp_ID Designation  Department        Age    Salary
0        1    1101     Manager    Accounts  50.000000  200000.0
1        2    1107     Officer          IT  30.000000   80000.0
2        3    1203     Officer          HR  28.000000  100000.0
3        4    1005     Manager          HR  45.000000  120000.0
4        5    2123  Office Boy    Accounts  27.000000   45000.0
5        6    2451  Accountant  Production  34.000000  100000.0
6        7    1111  Accountant    Accounts  35.869565  110000.0
7        8    1001     Officer          IT  25.000000   75000.0
8        9    1234     Manager          IT  23.000000  100000.0
9       10    2156    Engineer  Production  45.000000   89000.0
10      11    6543     Officer  Production  29.000000  100000.0
11      12    3214  Accountant     Account  49.000000  123000.0
12      13    2156    Engineer  Production  45.000000   89000.0
13      14    1098     Officer          IT  25.000000  100000.0
14      15    2912     Officer          IT  31.000000   90000.0
15      16    1222     Officer  Production  25.000000  100000.0
16      17    2156    Engineer  Production  45.000000   89000.0
17      18    2123  Office Boy    Accounts  27.000000   45000.0
18      19    2156    Engineer  Production  45.000000   89000.0
19      20    6543     Officer  Production  29.000000  100000.0
20      21    3214  Accountant     Account  49.000000  123000.0
21      22    3214  Accountant     Account  49.000000  123000.0
22      23    2156    Engineer  Production  45.000000   89000.0
23      24    1098     Officer          IT  25.000000  100000.0

In [109]:
car = pd.read_csv("car_data.csv")
car

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel
...,...,...,...,...,...,...
887,Ta,Tara,zest,"3,10,000",NaN,NaN
888,Tata Zest XM Diesel,Tata,2018,"2,60,000","27,000 kms",Diesel
889,Mahindra Quanto C8,Mahindra,2013,"3,90,000","40,000 kms",Diesel
890,Honda Amaze 1.2 E i VTEC,Honda,2014,"1,80,000",Petrol,NaN
891,Chevrolet Sail 1.2 LT ABS,Chevrolet,2014,"1,60,000",Petrol,NaN

In [111]:
car.head()

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel

In [113]:
car.shape

(892, 6)

In [114]:
car.info()

<class 'pandas.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        892 non-null    str
 1   company     892 non-null    str
 2   year        892 non-null    str
 3   Price       892 non-null    str
 4   kms_driven  840 non-null    str
 5   fuel_type   837 non-null    str
dtypes: str(6)
memory usage: 92.3 KB

In [115]:
car.columns

Index(['name', 'company', 'year', 'Price', 'kms_driven', 'fuel_type'], dtype='str')

### Duplicated

In [117]:
car.duplicated().sum()

np.int64(94)

In [119]:
car[car.duplicated()]

,name,company,year,Price,kms_driven,fuel_type
14,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
15,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
20,Mahindra Scorpio S10,Mahindra,2016,"3,50,000","43,000 kms",Diesel
24,Hyundai i20 Sportz 1.2,Hyundai,2012,"1,00,000","55,000 kms",Petrol
25,Hyundai i20 Sportz 1.2,Hyundai,2012,"1,00,000","55,000 kms",Petrol
...,...,...,...,...,...,...
626,Tata Sumo Gold EX BS IV,Tata,2012,"2,10,000","75,000 kms",Diesel
641,Maruti Suzuki Swift VDi BS IV,Maruti,2012,"2,80,000","48,006 kms",Diesel
727,Mahindra Scorpio S4,Mahindra,2015,"8,65,000","30,000 kms",Diesel
861,Hyundai Getz Prime 1.3 GLX,Hyundai,2009,"1,15,000","20,000 kms",Petrol
880,Maruti Suzuki Swift Dzire Tour VDi,Maruti,2009,"2,50,000","51,000 kms",Diesel

In [123]:
car[car.duplicated(subset=["name","company"])]

,name,company,year,Price,kms_driven,fuel_type
5,Ford EcoSport Titanium 1.5L TDCi,Ford,2015,Ask For Price,"59,000 kms",Diesel
14,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
15,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
20,Mahindra Scorpio S10,Mahindra,2016,"3,50,000","43,000 kms",Diesel
21,Mahindra Scorpio S10,Mahindra,2016,"3,10,000","39,522 kms",Diesel
...,...,...,...,...,...,...
876,Maruti Suzuki Dzire,Maruti,2016,"4,50,000","2,500 kms",Diesel
879,Maruti Suzuki Alto LXi BS III,Maruti,2005,"95,000","65,000 kms",Petrol
880,Maruti Suzuki Swift Dzire Tour VDi,Maruti,2009,"2,50,000","51,000 kms",Diesel
886,Toyota Corolla Altis,Toyota,2009,"3,00,000","1,32,000 kms",Petrol
889,Mahindra Quanto C8,Mahindra,2013,"3,90,000","40,000 kms",Diesel

In [124]:
car.loc[867,"name"]

'Mahindra Quanto C4'

In [127]:
car.drop_duplicates(inplace=True)

In [128]:
car

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel
...,...,...,...,...,...,...
887,Ta,Tara,zest,"3,10,000",NaN,NaN
888,Tata Zest XM Diesel,Tata,2018,"2,60,000","27,000 kms",Diesel
889,Mahindra Quanto C8,Mahindra,2013,"3,90,000","40,000 kms",Diesel
890,Honda Amaze 1.2 E i VTEC,Honda,2014,"1,80,000",Petrol,NaN
891,Chevrolet Sail 1.2 LT ABS,Chevrolet,2014,"1,60,000",Petrol,NaN

In [129]:
car.name.unique()

<ArrowStringArray>
[  'Hyundai Santro Xing XO eRLX Euro III',
                'Mahindra Jeep CL550 MDI',
             'Maruti Suzuki Alto 800 Vxi',
 'Hyundai Grand i10 Magna 1.2 Kappa VTVT',
       'Ford EcoSport Titanium 1.5L TDCi',
                              'Ford Figo',
                            'Hyundai Eon',
       'Ford EcoSport Ambiente 1.5L TDCi',
         'Maruti Suzuki Alto K10 VXi AMT',
            'Skoda Fabia Classic 1.2 MPI',
 ...
         'Mercedes Benz C Class 200 K MT',
                            'Skoda Fabia',
  'Maruti Suzuki Alto 800 Select Variant',
             'Maruti Suzuki Ritz VXI ABS',
                       'tata zest 2017 f',
              'Tata Indica V2 DLE BS III',
                                     'Ta',
                    'Tata Zest XM Diesel',
               'Honda Amaze 1.2 E i VTEC',
              'Chevrolet Sail 1.2 LT ABS']
Length: 525, dtype: str

In [138]:
car['name'].str.split().str[:3].str.join(' ')

0         Hyundai Santro Xing
1         Mahindra Jeep CL550
2          Maruti Suzuki Alto
3           Hyundai Grand i10
4      Ford EcoSport Titanium
                ...
887                        Ta
888              Tata Zest XM
889        Mahindra Quanto C8
890           Honda Amaze 1.2
891        Chevrolet Sail 1.2
Name: name, Length: 798, dtype: object