In [1]:
import pandas as pd
import numpy as np

### Finding Missing Data

In [2]:
data = {
    'A': [1, 2, 3, 4, 5],
    'B': [np.nan, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)

In [3]:
df.isna() #-> false shows not having any value while true shows it has

       A      B      C      D
0  False   True  False  False
1  False  False  False   True
2  False  False  False   True
3  False  False   True   True
4  False  False   True  False

In [4]:
df.isna().sum()

A    0
B    1
C    2
D    3
dtype: int64

In [5]:
df.isna().any()
#this checks does it have any null values in any columns

A    False
B     True
C     True
D     True
dtype: bool

### Removing Missing Data

In [6]:
df

   A    B    C    D
0  1  NaN  1.0  1.0
1  2  2.0  2.0  NaN
2  3  3.0  3.0  NaN
3  4  4.0  NaN  NaN
4  5  5.0  NaN  5.0

In [7]:
df.dropna() #removes null values row

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [8]:
# we can also set threshold for removing the values like if we giive 3 as threshold it will check whether the column has alteast 3 non null values if it has it will not remove it otherwise it will remove it
df.dropna(thresh=3)

   A    B    C    D
0  1  NaN  1.0  1.0
1  2  2.0  2.0  NaN
2  3  3.0  3.0  NaN
4  5  5.0  NaN  5.0

### Filling The Missing Data

In [9]:
df

   A    B    C    D
0  1  NaN  1.0  1.0
1  2  2.0  2.0  NaN
2  3  3.0  3.0  NaN
3  4  4.0  NaN  NaN
4  5  5.0  NaN  5.0

In [10]:
df.fillna(0)

   A    B    C    D
0  1  0.0  1.0  1.0
1  2  2.0  2.0  0.0
2  3  3.0  3.0  0.0
3  4  4.0  0.0  0.0
4  5  5.0  0.0  5.0

In [11]:
values = {
    'A' : 0,
    'B' : 100,
    'C' : 200,
    'D' : 300
}

In [ ]:
df.fillna(value=values) #column wise selection hota hai
# drop row wise hota hai

   A      B      C      D
0  1  100.0    1.0    1.0
1  2    2.0    2.0  300.0
2  3    3.0    3.0  300.0
3  4    4.0  200.0  300.0
4  5    5.0  200.0    5.0

In [13]:
df

   A    B    C    D
0  1  NaN  1.0  1.0
1  2  2.0  2.0  NaN
2  3  3.0  3.0  NaN
3  4  4.0  NaN  NaN
4  5  5.0  NaN  5.0

In [14]:
df.fillna(df.mean())

   A    B    C    D
0  1  3.5  1.0  1.0
1  2  2.0  2.0  3.0
2  3  3.0  3.0  3.0
3  4  4.0  2.0  3.0
4  5  5.0  2.0  5.0