### Classification In Machine Learning
   Classification algorithms are supervised machine learning techniques used to categorize data into distinct, predefined classes or labels

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
df = pd.read_csv('heart.csv')

In [3]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [4]:
df.duplicated().sum()

723

In [5]:
df = df.drop_duplicates()

In [6]:
x = df.drop(['target'],axis=1)
y = df.target

In [7]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.25,random_state=42)

In [8]:
x_train.shape,x_test.shape,y_test.shape,y_test.shape

((226, 13), (76, 13), (76,), (76,))

In [9]:
x_train

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
616,43,1,0,115,303,0,1,181,0,1.2,1,0,2
582,55,1,1,130,262,0,1,155,0,0.0,2,0,2
281,35,1,1,122,192,0,1,174,0,0.0,2,0,2
199,50,1,0,144,200,0,0,126,1,0.9,1,0,3
216,65,1,0,135,254,0,0,127,0,2.8,1,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
267,67,1,0,120,237,0,1,71,0,1.0,1,0,2
77,63,1,0,140,187,0,0,144,1,4.0,2,2,3
125,60,0,3,150,240,0,1,171,0,0.9,2,0,2
522,67,0,2,152,277,0,1,172,0,0.0,2,1,2
119,42,1,1,120,295,0,1,162,0,0.0,2,0,2

In [10]:
from sklearn.linear_model import LogisticRegression

In [11]:
lr = LogisticRegression()

In [12]:
import warnings
warnings.filterwarnings('ignore')

In [13]:
lr.fit(x_train,y_train)

LogisticRegression()

### Perfomance Evaluation
    In refreesion we used r2 score and mean absolute error to evaluate perfomance but in classification we will do something like this

In [14]:
from sklearn.metrics import confusion_matrix, recall_score, f1_score,accuracy_score,precision_score,classification_report

In [15]:
lr.predict(x_train)

array([1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 1], dtype=int64)

In [16]:
y_pred_train = lr.predict(x_train)

In [17]:
comparison = pd.DataFrame({
    "Actual": y_train.values,
    "Predicted": y_pred_train
})

comparison.head()

   Actual  Predicted
0       1          1
1       1          1
2       1          1
3       0          0
4       0          0

In [18]:
accuracy_score(y_train,y_pred_train)

0.8761061946902655

In [19]:
confusion_matrix(y_train,y_pred_train)

array([[ 78,  20],
       [  8, 120]], dtype=int64)

In [20]:
# tp  fp
# fn  tn

In [21]:
print(classification_report(y_train,y_pred_train))

              precision    recall  f1-score   support

           0       0.91      0.80      0.85        98
           1       0.86      0.94      0.90       128

    accuracy                           0.88       226
   macro avg       0.88      0.87      0.87       226
weighted avg       0.88      0.88      0.87       226

In [22]:
print(classification_report(y_train,y_pred_train))

              precision    recall  f1-score   support

           0       0.91      0.80      0.85        98
           1       0.86      0.94      0.90       128

    accuracy                           0.88       226
   macro avg       0.88      0.87      0.87       226
weighted avg       0.88      0.88      0.87       226

In [23]:
df.target.value_counts()

1    164
0    138
Name: target, dtype: int64

#### testing

In [24]:
lr.fit(x_test,y_test)

LogisticRegression()

In [25]:
lr.predict(x_test)

array([1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 0], dtype=int64)

In [26]:
y_pred_test = lr.predict(x_test)

In [27]:
comparison = pd.DataFrame({
    "Actual": y_train.values,
    "Predicted": y_pred_train
})

comparison.head()

   Actual  Predicted
0       1          1
1       1          1
2       1          1
3       0          0
4       0          0

In [28]:
accuracy_score(y_test,y_pred_test)

0.9078947368421053

In [29]:
df.duplicated().sum()

0

In [30]:
data = df.drop_duplicates()