### Pandas Class 3

In [80]:
import pandas as pd

In [124]:
data = pd.read_csv("movie.csv")

In [125]:
data.head()

,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Meta_score,Director,Star1,No_of_Votes,Gross
0,The Shawshank Redemption,1994,A,142 min,Drama,9.3,80.0,Frank Darabont,Tim Robbins,2343110,28341469.0
1,The Godfather,1972,A,175 min,"Crime, Drama",9.2,100.0,Francis Ford Coppola,Marlon Brando,1620367,134966411.0
2,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,84.0,Christopher Nolan,Christian Bale,2303232,534858444.0
3,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,90.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0
4,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,96.0,Sidney Lumet,Henry Fonda,689845,4360000.0

In [83]:
data.tail()

,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Meta_score,Director,Star1,No_of_Votes,Gross
995,Breakfast at Tiffany's,1961,A,115 min,"Comedy, Drama, Romance",7.6,76.0,Blake Edwards,Audrey Hepburn,166544,NaN
996,Giant,1956,G,201 min,"Drama, Western",7.6,84.0,George Stevens,Elizabeth Taylor,34075,NaN
997,From Here to Eternity,1953,Passed,118 min,"Drama, Romance, War",7.6,85.0,Fred Zinnemann,Burt Lancaster,43374,30500000.0
998,Lifeboat,1944,NaN,97 min,"Drama, War",7.6,78.0,Alfred Hitchcock,Tallulah Bankhead,26471,NaN
999,The 39 Steps,1935,NaN,86 min,"Crime, Mystery, Thriller",7.6,93.0,Alfred Hitchcock,Robert Donat,51853,NaN

### Unique or Non Unique

In [84]:
data.Series_Title

0      The Shawshank Redemption
1                 The Godfather
2               The Dark Knight
3        The Godfather: Part II
4                  12 Angry Men
                 ...
995      Breakfast at Tiffany's
996                       Giant
997       From Here to Eternity
998                    Lifeboat
999                The 39 Steps
Name: Series_Title, Length: 1000, dtype: str

In [126]:
data.Series_Title.unique()

<ArrowStringArray>
[                     'The Shawshank Redemption',
                                 'The Godfather',
                               'The Dark Knight',
                        'The Godfather: Part II',
                                  '12 Angry Men',
 'The Lord of the Rings: The Return of the King',
                                  'Pulp Fiction',
                              'Schindler's List',
                                     'Inception',
                                    'Fight Club',
 ...
                                  'Giù la testa',
                                'Kelly's Heroes',
                               'The Jungle Book',
                                        'Blowup',
                            'A Hard Day's Night',
                        'Breakfast at Tiffany's',
                                         'Giant',
                         'From Here to Eternity',
                                      'Lifeboat',
                                  'The 39 Steps']
Length: 999, dtype: str

In [86]:
data.size

11000

In [87]:
data.shape

(1000, 11)

In [88]:
data.Series_Title.nunique()

999

In [89]:
data.Series_Title.value_counts()

Series_Title
Drishyam                    2
The Shawshank Redemption    1
The Godfather               1
The Dark Knight             1
The Godfather: Part II      1
                           ..
Breakfast at Tiffany's      1
Giant                       1
From Here to Eternity       1
Lifeboat                    1
The 39 Steps                1
Name: count, Length: 999, dtype: int64

In [90]:
data.Series_Title.isna().sum()

np.int64(0)

In [91]:
data.Released_Year.unique()

<ArrowStringArray>
['1994', '1972', '2008', '1974', '1957', '2003', '1993', '2010', '1999',
 '2001', '1966', '2002', '1990', '1980', '1975', '2020', '2019', '2014',
 '1998', '1997', '1995', '1991', '1977', '1962', '1954', '1946', '2011',
 '2006', '2000', '1988', '1985', '1968', '1960', '1942', '1936', '1931',
 '2018', '2017', '2016', '2012', '2009', '2007', '1984', '1981', '1979',
 '1971', '1963', '1964', '1950', '1940', '2013', '2005', '2004', '1992',
 '1987', '1986', '1983', '1976', '1973', '1965', '1959', '1958', '1952',
 '1948', '1944', '1941', '1927', '1921', '2015', '1996', '1989', '1978',
 '1961', '1955', '1953', '1925', '1924', '1982', '1967', '1951', '1949',
 '1939', '1937', '1934', '1928', '1926', '1920', '1970', '1969', '1956',
 '1947', '1945', '1930', '1938', '1935', '1933', '1932', '1922', '1943',
   'PG']
Length: 100, dtype: str

In [92]:
data[data.Released_Year=="PG"]

,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Meta_score,Director,Star1,No_of_Votes,Gross
966,Apollo 13,PG,U,140 min,"Adventure, Drama, History",7.6,77.0,Ron Howard,Tom Hanks,269197,173837933.0

In [127]:
data[data.Released_Year == "PG"] = "1998"
data["Released_Year"] = data["Released_Year"].astype(int)

TypeError: Invalid value '1998' for dtype 'float64'

In [128]:
data.loc[966,"Released_Year"]

'1998'

In [129]:
data.Released_Year.unique()

<ArrowStringArray>
['1994', '1972', '2008', '1974', '1957', '2003', '1993', '2010', '1999',
 '2001', '1966', '2002', '1990', '1980', '1975', '2020', '2019', '2014',
 '1998', '1997', '1995', '1991', '1977', '1962', '1954', '1946', '2011',
 '2006', '2000', '1988', '1985', '1968', '1960', '1942', '1936', '1931',
 '2018', '2017', '2016', '2012', '2009', '2007', '1984', '1981', '1979',
 '1971', '1963', '1964', '1950', '1940', '2013', '2005', '2004', '1992',
 '1987', '1986', '1983', '1976', '1973', '1965', '1959', '1958', '1952',
 '1948', '1944', '1941', '1927', '1921', '2015', '1996', '1989', '1978',
 '1961', '1955', '1953', '1925', '1924', '1982', '1967', '1951', '1949',
 '1939', '1937', '1934', '1928', '1926', '1920', '1970', '1969', '1956',
 '1947', '1945', '1930', '1938', '1935', '1933', '1932', '1922', '1943']
Length: 99, dtype: str

In [ ]:
data.Released_Year.dtype

dtype('int64')

In [ ]:
data.loc[966]

Series_Title            1998
Released_Year           1998
Certificate             1998
Runtime                 1998
Genre                   1998
IMDB_Rating              7.6
Meta_score              77.0
Director          Ron Howard
Star1              Tom Hanks
No_of_Votes           269197
Gross            173837933.0
Name: 966, dtype: object

In [103]:
data.Runtime = data.Runtime.str.replace(" ","")

In [97]:
data.loc[998]

Series_Title              Lifeboat
Released_Year                 1944
Certificate                    NaN
Runtime                     97 min
Genre                   Drama, War
IMDB_Rating                    7.6
Meta_score                    78.0
Director          Alfred Hitchcock
Star1            Tallulah Bankhead
No_of_Votes                  26471
Gross                          NaN
Name: 998, dtype: object

In [104]:
data.Runtime.unique()

<ArrowStringArray>
[ '142',  '175',  '152',  '202',   '96',  '201',  '154',  '195',  '148',
  '139',
 ...
  '192',  '194',  '193',   '69',   '70',  '242',   '79',   '71', '1998',
   '78']
Length: 141, dtype: str

In [105]:
data.IMDB_Rating.isna()

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Name: IMDB_Rating, Length: 1000, dtype: bool

In [108]:
data.Gross.isna().sum()

np.int64(169)

In [130]:
data["Released_Year"] = data["Released_Year"].astype(int)
data[data.Released_Year >= 2000]

,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Meta_score,Director,Star1,No_of_Votes,Gross
2,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,84.0,Christopher Nolan,Christian Bale,2303232,534858444.0
5,The Lord of the Rings: The Return of the King,2003,U,201 min,"Action, Adventure, Drama",8.9,94.0,Peter Jackson,Elijah Wood,1642758,377845905.0
8,Inception,2010,UA,148 min,"Action, Adventure, Sci-Fi",8.8,74.0,Christopher Nolan,Leonardo DiCaprio,2067042,292576195.0
10,The Lord of the Rings: The Fellowship of the Ring,2001,U,178 min,"Action, Adventure, Drama",8.8,92.0,Peter Jackson,Elijah Wood,1661481,315544750.0
13,The Lord of the Rings: The Two Towers,2002,UA,179 min,"Action, Adventure, Drama",8.7,87.0,Peter Jackson,Elijah Wood,1485555,342551365.0
...,...,...,...,...,...,...,...,...,...,...,...
948,The Others,2001,PG-13,101 min,"Horror, Mystery, Thriller",7.6,74.0,Alejandro Amenábar,Nicole Kidman,337651,96522687.0
949,Blow,2001,R,124 min,"Biography, Crime, Drama",7.6,52.0,Ted Demme,Johnny Depp,240714,52990775.0
950,Enemy at the Gates,2001,A,131 min,"Drama, History, War",7.6,53.0,Jean-Jacques Annaud,Jude Law,243729,51401758.0
951,Minority Report,2002,A,145 min,"Action, Crime, Mystery",7.6,80.0,Steven Spielberg,Tom Cruise,508417,132072926.0
953,American Psycho,2000,A,101 min,"Comedy, Crime, Drama",7.6,64.0,Mary Harron,Christian Bale,490062,15070285.0

In [121]:
data[data.IMDB_Rating >= 9]

,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Meta_score,Director,Star1,No_of_Votes,Gross
0,The Shawshank Redemption,1994,A,142,Drama,9.3,80.0,Frank Darabont,Tim Robbins,2343110,28341469.0
1,The Godfather,1972,A,175,"Crime, Drama",9.2,100.0,Francis Ford Coppola,Marlon Brando,1620367,134966411.0
2,The Dark Knight,2008,UA,152,"Action, Crime, Drama",9.0,84.0,Christopher Nolan,Christian Bale,2303232,534858444.0
3,The Godfather: Part II,1974,A,202,"Crime, Drama",9.0,90.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0
4,12 Angry Men,1957,U,96,"Crime, Drama",9.0,96.0,Sidney Lumet,Henry Fonda,689845,4360000.0

In [137]:
# to find movies directed by christopher nolan
data[data.Director == "Christopher Nolan"]

,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Meta_score,Director,Star1,No_of_Votes,Gross
2,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,84.0,Christopher Nolan,Christian Bale,2303232,534858444.0
8,Inception,2010,UA,148 min,"Action, Adventure, Sci-Fi",8.8,74.0,Christopher Nolan,Leonardo DiCaprio,2067042,292576195.0
21,Interstellar,2014,UA,169 min,"Adventure, Drama, Sci-Fi",8.6,74.0,Christopher Nolan,Matthew McConaughey,1512360,188020017.0
36,The Prestige,2006,U,130 min,"Drama, Mystery, Sci-Fi",8.5,66.0,Christopher Nolan,Christian Bale,1190259,53089891.0
63,The Dark Knight Rises,2012,UA,164 min,"Action, Adventure",8.4,78.0,Christopher Nolan,Christian Bale,1516346,448139099.0
69,Memento,2000,UA,113 min,"Mystery, Thriller",8.4,80.0,Christopher Nolan,Guy Pearce,1125712,25544867.0
155,Batman Begins,2005,UA,140 min,"Action, Adventure",8.2,70.0,Christopher Nolan,Christian Bale,1308302,206852432.0
573,Dunkirk,2017,UA,106 min,"Action, Drama, History",7.8,94.0,Christopher Nolan,Fionn Whitehead,555092,188373161.0

In [133]:
# to find which genre has what type of data
data.Genre.value_counts()

Genre
Drama                        85
Drama, Romance               37
Comedy, Drama                35
Comedy, Drama, Romance       31
Action, Crime, Drama         30
                             ..
Action, Crime, Mystery        1
1998                          1
Animation, Drama, Romance     1
Drama, War, Western           1
Adventure, Comedy, War        1
Name: count, Length: 203, dtype: int64

In [139]:
# to find how many drama genre movies we have
count = data[data.Genre == "Drama"]
count

,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Meta_score,Director,Star1,No_of_Votes,Gross
0,The Shawshank Redemption,1994,A,142 min,Drama,9.3,80.0,Frank Darabont,Tim Robbins,2343110,28341469.0
9,Fight Club,1999,A,139 min,Drama,8.8,66.0,David Fincher,Brad Pitt,1854740,37030102.0
17,One Flew Over the Cuckoo's Nest,1975,A,133 min,Drama,8.7,83.0,Milos Forman,Jack Nicholson,918088,112000000.0
20,Soorarai Pottru,2020,U,153 min,Drama,8.6,NaN,Sudha Kongara,Suriya,54995,NaN
40,American History X,1998,R,119 min,Drama,8.5,62.0,Tony Kaye,Edward Norton,1034705,6719864.0
...,...,...,...,...,...,...,...,...,...,...,...
933,"Synecdoche, New York",2008,R,124 min,Drama,7.6,67.0,Charlie Kaufman,Philip Seymour Hoffman,83158,3081925.0
934,Mysterious Skin,2004,R,105 min,Drama,7.6,73.0,Gregg Araki,Brady Corbet,65939,697181.0
941,25th Hour,2002,R,135 min,Drama,7.6,68.0,Spike Lee,Edward Norton,169708,13060843.0
946,Y tu mamá también,2001,A,106 min,Drama,7.6,88.0,Alfonso Cuarón,Maribel Verdú,115827,13622333.0
981,On Golden Pond,1981,UA,109 min,Drama,7.6,68.0,Mark Rydell,Katharine Hepburn,27650,119285432.0

In [141]:
drama_movies = data[data["Genre"].str.contains("Drama", na=False)]
drama_movies

,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Meta_score,Director,Star1,No_of_Votes,Gross
0,The Shawshank Redemption,1994,A,142 min,Drama,9.3,80.0,Frank Darabont,Tim Robbins,2343110,28341469.0
1,The Godfather,1972,A,175 min,"Crime, Drama",9.2,100.0,Francis Ford Coppola,Marlon Brando,1620367,134966411.0
2,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,84.0,Christopher Nolan,Christian Bale,2303232,534858444.0
3,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,90.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0
4,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,96.0,Sidney Lumet,Henry Fonda,689845,4360000.0
...,...,...,...,...,...,...,...,...,...,...,...
993,Blowup,1966,A,111 min,"Drama, Mystery, Thriller",7.6,82.0,Michelangelo Antonioni,David Hemmings,56513,NaN
995,Breakfast at Tiffany's,1961,A,115 min,"Comedy, Drama, Romance",7.6,76.0,Blake Edwards,Audrey Hepburn,166544,NaN
996,Giant,1956,G,201 min,"Drama, Western",7.6,84.0,George Stevens,Elizabeth Taylor,34075,NaN
997,From Here to Eternity,1953,Passed,118 min,"Drama, Romance, War",7.6,85.0,Fred Zinnemann,Burt Lancaster,43374,30500000.0
998,Lifeboat,1944,NaN,97 min,"Drama, War",7.6,78.0,Alfred Hitchcock,Tallulah Bankhead,26471,NaN

In [145]:
# sort by imdb rating in descending order
data.sort_values(by="IMDB_Rating",ascending=False)

,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Meta_score,Director,Star1,No_of_Votes,Gross
0,The Shawshank Redemption,1994,A,142 min,Drama,9.3,80.0,Frank Darabont,Tim Robbins,2343110,28341469.0
1,The Godfather,1972,A,175 min,"Crime, Drama",9.2,100.0,Francis Ford Coppola,Marlon Brando,1620367,134966411.0
2,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,84.0,Christopher Nolan,Christian Bale,2303232,534858444.0
3,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,90.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0
4,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,96.0,Sidney Lumet,Henry Fonda,689845,4360000.0
...,...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,A,115 min,"Comedy, Drama, Romance",7.6,76.0,Blake Edwards,Audrey Hepburn,166544,NaN
996,Giant,1956,G,201 min,"Drama, Western",7.6,84.0,George Stevens,Elizabeth Taylor,34075,NaN
997,From Here to Eternity,1953,Passed,118 min,"Drama, Romance, War",7.6,85.0,Fred Zinnemann,Burt Lancaster,43374,30500000.0
998,Lifeboat,1944,NaN,97 min,"Drama, War",7.6,78.0,Alfred Hitchcock,Tallulah Bankhead,26471,NaN
999,The 39 Steps,1935,NaN,86 min,"Crime, Mystery, Thriller",7.6,93.0,Alfred Hitchcock,Robert Donat,51853,NaN

In [148]:
data[data.Runtime.max()]

KeyError: '99 min'

In [149]:
data[data.Star1 .str.contains("Leonardo")]

,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Meta_score,Director,Star1,No_of_Votes,Gross
8,Inception,2010,UA,148 min,"Action, Adventure, Sci-Fi",8.8,74.0,Christopher Nolan,Leonardo DiCaprio,2067042,292576195.0
37,The Departed,2006,A,151 min,"Crime, Drama, Thriller",8.5,85.0,Martin Scorsese,Leonardo DiCaprio,1189773,132384315.0
145,Shutter Island,2010,A,138 min,"Mystery, Thriller",8.2,63.0,Martin Scorsese,Leonardo DiCaprio,1129894,128012934.0
147,The Wolf of Wall Street,2013,A,180 min,"Biography, Crime, Drama",8.2,75.0,Martin Scorsese,Leonardo DiCaprio,1187498,116900694.0
243,Catch Me If You Can,2002,A,141 min,"Biography, Crime, Drama",8.1,75.0,Steven Spielberg,Leonardo DiCaprio,832846,164615351.0
343,The Revenant,2015,A,156 min,"Action, Adventure, Drama",8.0,76.0,Alejandro G. Iñárritu,Leonardo DiCaprio,705589,183637894.0
361,Blood Diamond,2006,A,143 min,"Adventure, Drama, Thriller",8.0,64.0,Edward Zwick,Leonardo DiCaprio,499439,57366262.0
652,Titanic,1997,UA,194 min,"Drama, Romance",7.8,75.0,James Cameron,Leonardo DiCaprio,1046089,659325379.0
879,Once Upon a Time... in Hollywood,2019,A,161 min,"Comedy, Drama",7.6,83.0,Quentin Tarantino,Leonardo DiCaprio,551309,142502728.0

In [150]:
import numpy as np

NameError: name 'ist' is not defined

In [151]:
# movies released between 2010 and 2014
data[(data.Released_Year >= 2010) & (data.Released_Year <= 2014)]

,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Meta_score,Director,Star1,No_of_Votes,Gross
8,Inception,2010,UA,148 min,"Action, Adventure, Sci-Fi",8.8,74.0,Christopher Nolan,Leonardo DiCaprio,2067042,292576195.0
21,Interstellar,2014,UA,169 min,"Adventure, Drama, Sci-Fi",8.6,74.0,Christopher Nolan,Matthew McConaughey,1512360,188020017.0
34,Whiplash,2014,A,106 min,"Drama, Music",8.5,88.0,Damien Chazelle,Miles Teller,717585,13092000.0
35,The Intouchables,2011,UA,112 min,"Biography, Comedy, Drama",8.5,57.0,Olivier Nakache,Éric Toledano,760360,13182281.0
62,Django Unchained,2012,A,165 min,"Drama, Western",8.4,81.0,Quentin Tarantino,Jamie Foxx,1357682,162805434.0
...,...,...,...,...,...,...,...,...,...,...,...
906,Despicable Me,2010,U,95 min,"Animation, Comedy, Crime",7.6,72.0,Pierre Coffin,Chris Renaud,500851,251513985.0
907,50/50,2011,R,100 min,"Comedy, Drama, Romance",7.6,72.0,Jonathan Levine,Joseph Gordon-Levitt,315426,35014192.0
908,Kick-Ass,2010,UA,117 min,"Action, Comedy, Crime",7.6,66.0,Matthew Vaughn,Aaron Taylor-Johnson,524081,48071303.0
910,Moneyball,2011,PG-13,133 min,"Biography, Drama, Sport",7.6,87.0,Bennett Miller,Brad Pitt,369529,75605492.0
911,La piel que habito,2011,R,120 min,"Drama, Horror, Thriller",7.6,70.0,Pedro Almodóvar,Antonio Banderas,138959,3185812.0

In [152]:
import numpy as np
data["Random_Number"] = np.random.randint(1,1001,size=len(data))

In [153]:
data

,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Meta_score,Director,Star1,No_of_Votes,Gross,Random_Number
0,The Shawshank Redemption,1994,A,142 min,Drama,9.3,80.0,Frank Darabont,Tim Robbins,2343110,28341469.0,101
1,The Godfather,1972,A,175 min,"Crime, Drama",9.2,100.0,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,639
2,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,84.0,Christopher Nolan,Christian Bale,2303232,534858444.0,302
3,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,90.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,220
4,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,96.0,Sidney Lumet,Henry Fonda,689845,4360000.0,515
...,...,...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,A,115 min,"Comedy, Drama, Romance",7.6,76.0,Blake Edwards,Audrey Hepburn,166544,NaN,167
996,Giant,1956,G,201 min,"Drama, Western",7.6,84.0,George Stevens,Elizabeth Taylor,34075,NaN,518
997,From Here to Eternity,1953,Passed,118 min,"Drama, Romance, War",7.6,85.0,Fred Zinnemann,Burt Lancaster,43374,30500000.0,751
998,Lifeboat,1944,NaN,97 min,"Drama, War",7.6,78.0,Alfred Hitchcock,Tallulah Bankhead,26471,NaN,341
999,The 39 Steps,1935,NaN,86 min,"Crime, Mystery, Thriller",7.6,93.0,Alfred Hitchcock,Robert Donat,51853,NaN,762