# Data Frames
    When we combine multiple series it becomes a data frame

In [2]:
import pandas as pd
import numpy as np

### Creating A DataFrame

In [3]:
data = {
    'Name': ['John','Anna','Peter','Linda'],
    'Age' : [20,34,19,20],
    'City' : ['New York','Paris','Berlin','London'],
    'Salary' : [45000,30000,25000,80000]
}

In [4]:
df = pd.DataFrame(data)

In [5]:
df

    Name  Age      City  Salary
0   John   20  New York   45000
1   Anna   34     Paris   30000
2  Peter   19    Berlin   25000
3  Linda   20    London   80000

In [6]:
#  we can use it also like using a list

In [7]:
data_list2 = [
    ['John',28,'New York',60000],
    ['Anna',25,'Paris',80000],
    ['Peter',19,'Berlin',62000],
    ['Linda',20,'London',80000]
]
df2 = pd.DataFrame(data_list2)
df2
# the header disapear as u can see in the above sell we have the column names but no issue we can name them
columns = ['Name','Age','City','Salary']
df2 = pd.DataFrame(data_list2,columns =columns)
df2

    Name  Age      City  Salary
0   John   28  New York   60000
1   Anna   25     Paris   80000
2  Peter   19    Berlin   62000
3  Linda   20    London   80000

### Selection And Indexing of Columns

In [8]:
df2

    Name  Age      City  Salary
0   John   28  New York   60000
1   Anna   25     Paris   80000
2  Peter   19    Berlin   62000
3  Linda   20    London   80000

In [9]:
# df2['Column Name']
df2['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: str

In [10]:
df['City']

0    New York
1       Paris
2      Berlin
3      London
Name: City, dtype: str

In [11]:
# targeting multiple columns
# we can do it using [['1st Column Name','Second Column Name']]
df2[['Name','Age']]

    Name  Age
0   John   28
1   Anna   25
2  Peter   19
3  Linda   20

### Creating a New Column

In [12]:
df2['Designation'] = ['Clerk','Engineer','Dr','Professor']
df2

    Name  Age      City  Salary Designation
0   John   28  New York   60000       Clerk
1   Anna   25     Paris   80000    Engineer
2  Peter   19    Berlin   62000          Dr
3  Linda   20    London   80000   Professor

    In the above approach the only catch is u have to provide same number of data's not less not more the exact number of data otherwise it will throw an exception

### Removing Columns

In [13]:
df2.drop('Designation',axis=1)
# axis = 1 means column by default the axis is zero

    Name  Age      City  Salary
0   John   28  New York   60000
1   Anna   25     Paris   80000
2  Peter   19    Berlin   62000
3  Linda   20    London   80000

In [14]:
df2
#  here we can see the designation is present to fix this there is a keyword known as inplace
df2.drop('Designation',axis=1,inplace=True)

In [15]:
df2

    Name  Age      City  Salary
0   John   28  New York   60000
1   Anna   25     Paris   80000
2  Peter   19    Berlin   62000
3  Linda   20    London   80000

In [16]:
# now lets remove john's row but definetly not from our main data for which i will not be using inplace to preserve my data
# 0 means first row i ndex
df2.drop(0,axis=0)
# here u can see john is removed

    Name  Age    City  Salary
1   Anna   25   Paris   80000
2  Peter   19  Berlin   62000
3  Linda   20  London   80000

### Selecting Rows

In [17]:
# To select rows we need to use loc and iloc [] to select multiple columns we need to add list inside of a list [[]]
df2.loc[0]
# here we are using 0 1 2 because the default index we have is 0 1 2 on the other hand if the index elements were different from 0 1 2 we could use them if i am not wrong i would request u to verify them. iloc on the other hand uses index values 0 1 2 3 even if the index values are not like this but it works like index of array

Name          John
Age             28
City      New York
Salary       60000
Name: 0, dtype: object

In [18]:
df2.loc[[0,1]]

   Name  Age      City  Salary
0  John   28  New York   60000
1  Anna   25     Paris   80000

In [27]:
df2.iloc[3]

Name       Linda
Age           20
City      London
Salary     80000
Name: 3, dtype: object

### Selecting Subsets Of Rows And Columns

    How to select particular portion of rows or columns to do this we have to select both rows and columns at the same tiem

In [20]:
df2.loc[[0,1]][['City','Salary']]
# we have selected these columns
# df2.loc[[0,1]] -> this part selects the rows to select
# [['City','Salary']] -> this part selects the columns u want to see
# Practice set select row number 3 and 4. And for column name and age

       City  Salary
0  New York   60000
1     Paris   80000

In [21]:
df2.loc[[2,3]][['Name','Age']]

    Name  Age
2  Peter   19
3  Linda   20

In [22]:
df2.iloc[[2,3]][['Name','City']]

    Name    City
2  Peter  Berlin
3  Linda  London

In [23]:
df2.loc[0:4, ['Name', 'City']]
# to select two or more rows we do this

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

### Conditional Selection

In [24]:
# in pandas to target a condition we write like this
# data frame name first then brackets then again name then the column name then the condition just like this i have done an example below
df2[df2['Age'] >= 25]

   Name  Age      City  Salary
0  John   28  New York   60000
1  Anna   25     Paris   80000

In [25]:
df2[df2['Age'] >= 25 & df2['City'] == "Paris"]

TypeError: operation 'rand_' not supported for dtype 'str' with object of type <class 'int'>

In [ ]:
df2[(df2['Age'] >= 25) & (df2['City'] == "Paris")] #to solve the above error we need to do is wrap the condition in round bracket

   Name  Age   City  Salary
1  Anna   25  Paris   80000